CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(80) NOT NULL UNIQUE);
;
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"));
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id"), "group_id" integer NOT NULL REFERENCES "auth_group" ("id"));
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"));
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "codename" varchar(100) NOT NULL, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id"));
CREATE UNIQUE INDEX "auth_group_permissions_group_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_0e939a4f" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_8373b171" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_e8701ad4" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_0e939a4f" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_e8701ad4" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_8373b171" ON "auth_user_user_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_permission_content_type_id_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_417f1b1c" ON "auth_permission" ("content_type_id");
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id"), "user_id" integer NOT NULL REFERENCES "auth_user" ("id"), "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_417f1b1c" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_e8701ad4" ON "django_admin_log" ("user_id");
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "username" varchar(30) NOT NULL UNIQUE);
;
CREATE TABLE "Billingbase" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL UNIQUE, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
;
CREATE TABLE "Bookingstatus" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL, "is_active" bool NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE TABLE "Category" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL UNIQUE, "picture" varchar(100) NOT NULL, "is_active" bool NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
;
CREATE TABLE "City" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL UNIQUE, "is_active" bool NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "city_code" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
;
CREATE TABLE "Companytype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL UNIQUE, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
;
CREATE TABLE "Dutyslipstatus" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL, "is_active" bool NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE TABLE "Invoicestatus" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL, "is_active" bool NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE TABLE "rapido_location" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "street_address" varchar(200) NULL, "landmark" varchar(128) NOT NULL, "area" varchar(128) NOT NULL, "city" varchar(128) NOT NULL, "state" varchar(128) NOT NULL, "country" varchar(128) NOT NULL, "pincode" integer NOT NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE TABLE "Servicetype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL UNIQUE, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
;
CREATE TABLE "Slab" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL, "is_active" bool NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE TABLE "Travelservicetype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL UNIQUE, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
;
CREATE TABLE "Vehicle_varient" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE TABLE "Vendortype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL, "is_active" bool NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE INDEX "Billingbase_e93cb7eb" ON "Billingbase" ("created_by_id");
CREATE INDEX "Billingbase_9ccf0ba6" ON "Billingbase" ("updated_by_id");
CREATE INDEX "Bookingstatus_e93cb7eb" ON "Bookingstatus" ("created_by_id");
CREATE INDEX "Bookingstatus_9ccf0ba6" ON "Bookingstatus" ("updated_by_id");
CREATE INDEX "Category_e93cb7eb" ON "Category" ("created_by_id");
CREATE INDEX "Category_9ccf0ba6" ON "Category" ("updated_by_id");
CREATE INDEX "City_e93cb7eb" ON "City" ("created_by_id");
CREATE INDEX "City_9ccf0ba6" ON "City" ("updated_by_id");
CREATE INDEX "Companytype_e93cb7eb" ON "Companytype" ("created_by_id");
CREATE INDEX "Companytype_9ccf0ba6" ON "Companytype" ("updated_by_id");
CREATE INDEX "Dutyslipstatus_e93cb7eb" ON "Dutyslipstatus" ("created_by_id");
CREATE INDEX "Dutyslipstatus_9ccf0ba6" ON "Dutyslipstatus" ("updated_by_id");
CREATE INDEX "Invoicestatus_e93cb7eb" ON "Invoicestatus" ("created_by_id");
CREATE INDEX "Invoicestatus_9ccf0ba6" ON "Invoicestatus" ("updated_by_id");
CREATE INDEX "rapido_location_e93cb7eb" ON "rapido_location" ("created_by_id");
CREATE INDEX "rapido_location_9ccf0ba6" ON "rapido_location" ("updated_by_id");
CREATE INDEX "Servicetype_e93cb7eb" ON "Servicetype" ("created_by_id");
CREATE INDEX "Servicetype_9ccf0ba6" ON "Servicetype" ("updated_by_id");
CREATE INDEX "Slab_e93cb7eb" ON "Slab" ("created_by_id");
CREATE INDEX "Slab_9ccf0ba6" ON "Slab" ("updated_by_id");
CREATE INDEX "Travelservicetype_e93cb7eb" ON "Travelservicetype" ("created_by_id");
CREATE INDEX "Travelservicetype_9ccf0ba6" ON "Travelservicetype" ("updated_by_id");
CREATE INDEX "Vehicle_varient_e93cb7eb" ON "Vehicle_varient" ("created_by_id");
CREATE INDEX "Vehicle_varient_9ccf0ba6" ON "Vehicle_varient" ("updated_by_id");
CREATE TABLE "Vehicle" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "vehicle_no" varchar(10) NOT NULL UNIQUE, "vehicle_picture" varchar(100) NULL, "vehicle_colour" varchar(128) NULL, "vehicle_ownername" varchar(128) NULL, "vehicle_owner_phoneno" varchar(10) NULL, "seat_capacity" integer NOT NULL, "insurance_expire_date" date NOT NULL, "tax_expire_date" date NOT NULL, "vehicle_engine_no" varchar(30) NOT NULL, "is_active" bool NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"), "vehicle_belongsto_id" integer NOT NULL REFERENCES "Vendor" ("id"), "vehicle_modelname_id" integer NOT NULL REFERENCES "Vehicle_varient" ("id"));
;
CREATE INDEX "Vehicle_e93cb7eb" ON "Vehicle" ("created_by_id");
CREATE INDEX "Vehicle_9ccf0ba6" ON "Vehicle" ("updated_by_id");
CREATE INDEX "Vehicle_4d0a36e8" ON "Vehicle" ("vehicle_belongsto_id");
CREATE INDEX "Vehicle_21dcf1c0" ON "Vehicle" ("vehicle_modelname_id");
CREATE TABLE "Invoice" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "created_by_ip_address" varchar(128) NULL, "updated_date" datetime NULL, "updated_by_ip_address" varchar(128) NULL, "comment" varchar(128) NOT NULL, "booking_id" integer NOT NULL REFERENCES "Bookings" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "dutyslip_id" integer NOT NULL REFERENCES "Dutyslip" ("id"), "status_id" integer NOT NULL REFERENCES "Invoicestatus" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE INDEX "Invoice_b0060af7" ON "Invoice" ("booking_id");
CREATE INDEX "Invoice_e93cb7eb" ON "Invoice" ("created_by_id");
CREATE INDEX "Invoice_e1bd45e8" ON "Invoice" ("dutyslip_id");
CREATE INDEX "Invoice_dc91ed4b" ON "Invoice" ("status_id");
CREATE INDEX "Invoice_9ccf0ba6" ON "Invoice" ("updated_by_id");
CREATE TABLE "Outstation_ratecard" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "vehicle_varient" varchar(128) NULL, "min_km" real NOT NULL, "perkm_rate" real NOT NULL, "extrakm_rate" real NOT NULL, "day_batta" real NOT NULL, "night_batta" real NOT NULL, "category_id" integer NOT NULL REFERENCES "Category" ("id"), "city_id" integer NOT NULL REFERENCES "City" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "service_type_id" integer NOT NULL REFERENCES "Travelservicetype" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE UNIQUE INDEX "Outstation_ratecard_city_id_74a9da89_uniq" ON "Outstation_ratecard" ("city_id", "category_id");
CREATE INDEX "Outstation_ratecard_b583a629" ON "Outstation_ratecard" ("category_id");
CREATE INDEX "Outstation_ratecard_c7141997" ON "Outstation_ratecard" ("city_id");
CREATE INDEX "Outstation_ratecard_e93cb7eb" ON "Outstation_ratecard" ("created_by_id");
CREATE INDEX "Outstation_ratecard_8f1d2d79" ON "Outstation_ratecard" ("service_type_id");
CREATE INDEX "Outstation_ratecard_9ccf0ba6" ON "Outstation_ratecard" ("updated_by_id");
CREATE TABLE "Company_outstation_ratecard" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "vehicle_varient" varchar(128) NULL, "min_km" real NOT NULL, "perkm_rate" real NOT NULL, "extrakm_rate" real NOT NULL, "day_batta" real NOT NULL, "night_batta" real NOT NULL, "gst_no" varchar(128) NULL, "category_id" integer NOT NULL REFERENCES "Category" ("id"), "city_id" integer NOT NULL REFERENCES "City" ("id"), "company_id" integer NOT NULL REFERENCES "Company" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "service_type_id" integer NOT NULL REFERENCES "Travelservicetype" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE UNIQUE INDEX "Company_outstation_ratecard_company_id_a20e72be_uniq" ON "Company_outstation_ratecard" ("company_id", "city_id", "category_id");
CREATE INDEX "Company_outstation_ratecard_b583a629" ON "Company_outstation_ratecard" ("category_id");
CREATE INDEX "Company_outstation_ratecard_c7141997" ON "Company_outstation_ratecard" ("city_id");
CREATE INDEX "Company_outstation_ratecard_447d3092" ON "Company_outstation_ratecard" ("company_id");
CREATE INDEX "Company_outstation_ratecard_e93cb7eb" ON "Company_outstation_ratecard" ("created_by_id");
CREATE INDEX "Company_outstation_ratecard_8f1d2d79" ON "Company_outstation_ratecard" ("service_type_id");
CREATE INDEX "Company_outstation_ratecard_9ccf0ba6" ON "Company_outstation_ratecard" ("updated_by_id");
CREATE TABLE "Company_airport_ratecard" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "vehicle_varient" varchar(128) NULL, "base_rate" real NOT NULL, "gst_no" varchar(128) NULL, "category_id" integer NOT NULL REFERENCES "Category" ("id"), "city_id" integer NOT NULL REFERENCES "City" ("id"), "company_id" integer NOT NULL REFERENCES "Company" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "service_type_id" integer NOT NULL REFERENCES "Travelservicetype" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE UNIQUE INDEX "Company_airport_ratecard_company_id_9a7d9f5e_uniq" ON "Company_airport_ratecard" ("company_id", "city_id", "category_id");
CREATE INDEX "Company_airport_ratecard_b583a629" ON "Company_airport_ratecard" ("category_id");
CREATE INDEX "Company_airport_ratecard_c7141997" ON "Company_airport_ratecard" ("city_id");
CREATE INDEX "Company_airport_ratecard_447d3092" ON "Company_airport_ratecard" ("company_id");
CREATE INDEX "Company_airport_ratecard_e93cb7eb" ON "Company_airport_ratecard" ("created_by_id");
CREATE INDEX "Company_airport_ratecard_8f1d2d79" ON "Company_airport_ratecard" ("service_type_id");
CREATE INDEX "Company_airport_ratecard_9ccf0ba6" ON "Company_airport_ratecard" ("updated_by_id");
CREATE TABLE "Chauffeur" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "chauffeur_name" varchar(128) NOT NULL, "chauffeur_phoneno" varchar(10) NOT NULL UNIQUE, "chauffeur_picture" varchar(100) NOT NULL, "chauffeur_drivinglicense" varchar(20) NOT NULL, "chauffeur_drivinglicense_expire_date" date NOT NULL, "chauffeur_badgeno" varchar(10) NOT NULL, "chauffeur_badge_expired_date" date NOT NULL, "likes" integer NOT NULL, "ratings" integer NOT NULL, "is_active" bool NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "chauffeur_address_id" integer NULL REFERENCES "rapido_location" ("id"), "chauffeur_belongsto_id" integer NOT NULL REFERENCES "Vendor" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
;
CREATE UNIQUE INDEX "Chauffeur_chauffeur_name_281ccded_uniq" ON "Chauffeur" ("chauffeur_name", "chauffeur_drivinglicense");
CREATE INDEX "Chauffeur_168c7042" ON "Chauffeur" ("chauffeur_address_id");
CREATE INDEX "Chauffeur_eb2fb200" ON "Chauffeur" ("chauffeur_belongsto_id");
CREATE INDEX "Chauffeur_e93cb7eb" ON "Chauffeur" ("created_by_id");
CREATE INDEX "Chauffeur_9ccf0ba6" ON "Chauffeur" ("updated_by_id");
CREATE TABLE "Airport_ratecard" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "vehicle_varient" varchar(128) NULL, "base_rate" real NOT NULL, "category_id" integer NOT NULL REFERENCES "Category" ("id"), "city_id" integer NOT NULL REFERENCES "City" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "service_type_id" integer NOT NULL REFERENCES "Travelservicetype" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE UNIQUE INDEX "Airport_ratecard_city_id_0c900335_uniq" ON "Airport_ratecard" ("city_id", "category_id");
CREATE INDEX "Airport_ratecard_b583a629" ON "Airport_ratecard" ("category_id");
CREATE INDEX "Airport_ratecard_c7141997" ON "Airport_ratecard" ("city_id");
CREATE INDEX "Airport_ratecard_e93cb7eb" ON "Airport_ratecard" ("created_by_id");
CREATE INDEX "Airport_ratecard_8f1d2d79" ON "Airport_ratecard" ("service_type_id");
CREATE INDEX "Airport_ratecard_9ccf0ba6" ON "Airport_ratecard" ("updated_by_id");
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
;
CREATE INDEX "django_session_de54fa62" ON "django_session" ("expire_date");
CREATE TABLE "Bookings" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "booking_id" varchar(20) NOT NULL UNIQUE, "created_date" datetime NOT NULL, "created_by_ip_address" varchar(128) NULL, "updated_date" datetime NULL, "updated_by_ip_address" varchar(128) NULL, "booking_from" varchar(128) NULL, "booking_phoneno" varchar(10) NULL, "booking_email" varchar(254) NULL, "guest_name" varchar(128) NOT NULL, "guest_gender" varchar(128) NOT NULL, "guest_phoneno" varchar(10) NOT NULL, "guest_email" varchar(254) NULL, "pickup_date_time" datetime NOT NULL, "pick_up_location" varchar(200) NOT NULL, "drop_location" varchar(200) NULL, "requested_vehicle_model" varchar(128) NULL, "comment" varchar(200) NULL, "billing_base_id" integer NOT NULL REFERENCES "Billingbase" ("id"), "category_id" integer NOT NULL REFERENCES "Category" ("id"), "company_id" integer NULL REFERENCES "Company" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "service_type_id" integer NOT NULL REFERENCES "Servicetype" ("id"), "servicing_city_id" integer NOT NULL REFERENCES "City" ("id"), "status_id" integer NOT NULL REFERENCES "Bookingstatus" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"), "remarks" varchar(200) NULL);
;
CREATE INDEX "Bookings_dc0a66b6" ON "Bookings" ("billing_base_id");
CREATE INDEX "Bookings_b583a629" ON "Bookings" ("category_id");
CREATE INDEX "Bookings_447d3092" ON "Bookings" ("company_id");
CREATE INDEX "Bookings_e93cb7eb" ON "Bookings" ("created_by_id");
CREATE INDEX "Bookings_8f1d2d79" ON "Bookings" ("service_type_id");
CREATE INDEX "Bookings_2bc4f2e3" ON "Bookings" ("servicing_city_id");
CREATE INDEX "Bookings_dc91ed4b" ON "Bookings" ("status_id");
CREATE INDEX "Bookings_9ccf0ba6" ON "Bookings" ("updated_by_id");
CREATE TABLE "Company" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "company_name" varchar(128) NOT NULL, "company_logo" varchar(100) NULL, "company_email" varchar(128) NOT NULL, "company_manager_name" varchar(128) NOT NULL, "company_manager_mobileno" varchar(10) NOT NULL, "company_manager_email" varchar(254) NOT NULL, "company_payment_type" varchar(128) NOT NULL, "company_agreement_start_date" date NOT NULL, "company_agreement_end_date" date NOT NULL, "travelling_time_treshhold" integer NOT NULL, "status" bool NOT NULL, "company_documents" varchar(100) NULL, "remarks" varchar(200) NULL, "is_active" bool NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "gst" varchar(20) NULL UNIQUE, "pan" varchar(20) NULL UNIQUE, "company_code" varchar(20) NOT NULL, "company_address_id" integer NOT NULL REFERENCES "rapido_location" ("id"), "company_type_id" integer NOT NULL REFERENCES "Companytype" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"), "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id"), "company_phoneno" varchar(15) NOT NULL);
;
;
;
CREATE INDEX "Company_a3402add" ON "Company" ("company_address_id");
CREATE INDEX "Company_067bfe8b" ON "Company" ("company_type_id");
CREATE INDEX "Company_e93cb7eb" ON "Company" ("created_by_id");
CREATE INDEX "Company_9ccf0ba6" ON "Company" ("updated_by_id");
CREATE TABLE "Bookingsms" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "created_by_ip_address" varchar(128) NULL, "updated_date" datetime NULL, "updated_by_ip_address" varchar(128) NULL, "emailsent" bool NOT NULL, "smssent" bool NOT NULL, "smsdelivery" bool NOT NULL, "status" varchar(128) NOT NULL, "booking_id" integer NOT NULL UNIQUE REFERENCES "Bookings" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
;
CREATE TABLE "Dutyslip" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "dutyslip_id" varchar(20) NOT NULL, "created_date" datetime NOT NULL, "created_by_ip_address" varchar(128) NULL, "updated_date" datetime NULL, "updated_by_ip_address" varchar(128) NULL, "allocated_vehicle" varchar(128) NOT NULL, "vehicle_colour" varchar(128) NOT NULL, "vehicle_no" varchar(128) NOT NULL, "chauffeur_name" varchar(128) NOT NULL, "chauffeur_phoneno" varchar(10) NOT NULL, "date_out" date NULL, "date_in" date NULL, "total_days" real NULL, "opening_time" time NULL, "closing_time" time NULL, "total_hrs" real NULL, "opening_km" real NULL, "closing_km" real NULL, "total_kms" real NULL, "point_opening_km" real NULL, "point_closing_km" real NULL, "total_point_kms" real NULL, "point_opening_hrs" time NULL, "point_closing_hrs" time NULL, "total_point_hrs" real NULL, "extra_hr" real NULL, "extra_km" real NULL, "package" varchar(128) NULL, "package_rate" real NULL, "extra_km_rate" real NULL, "extra_hr_rate" real NULL, "parking" real NULL, "itinerary" real NULL, "miscellaneous" real NULL, "gst_percentage" real NULL, "gst_Rs" real NULL, "total_amount" real NULL, "comment" varchar(128) NULL, "cgst_percentage" real NULL, "cgst_Rs" real NULL, "sgst_percentage" real NULL, "sgst_Rs" real NULL, "fgr" real NULL, "daybhatta" real NULL, "nightbhatta" real NULL, "subtotal" real NULL, "discount" real NULL, "extra_km_runrate" real NULL, "extra_hr_runrate" real NULL, "permit" real NULL, "amount_tobe_paid" real NULL, "km_used" real NULL, "hrs_used" real NULL, "booking_id" integer NOT NULL UNIQUE REFERENCES "Bookings" ("id"), "category_id" integer NOT NULL REFERENCES "Category" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "status_id" integer NOT NULL REFERENCES "Dutyslipstatus" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"), "vendor_id" integer NOT NULL REFERENCES "Vendor" ("id"), "chauffeur_drivinglicense" varchar(128) NULL);
;
CREATE INDEX "Bookingsms_e93cb7eb" ON "Bookingsms" ("created_by_id");
CREATE INDEX "Bookingsms_9ccf0ba6" ON "Bookingsms" ("updated_by_id");
CREATE INDEX "Dutyslip_b583a629" ON "Dutyslip" ("category_id");
CREATE INDEX "Dutyslip_e93cb7eb" ON "Dutyslip" ("created_by_id");
CREATE INDEX "Dutyslip_dc91ed4b" ON "Dutyslip" ("status_id");
CREATE INDEX "Dutyslip_9ccf0ba6" ON "Dutyslip" ("updated_by_id");
CREATE INDEX "Dutyslip_96b1f972" ON "Dutyslip" ("vendor_id");
CREATE TABLE "Dutyslipsms" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "created_by_ip_address" varchar(128) NULL, "updated_date" datetime NULL, "updated_by_ip_address" varchar(128) NULL, "emailsent" bool NOT NULL, "usersmssent" bool NOT NULL, "usersmsdelivery" bool NOT NULL, "userstatus" varchar(128) NULL, "driversmssent" bool NOT NULL, "driversmsdelivery" bool NOT NULL, "driverstatus" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "dutyslip_id" integer NOT NULL UNIQUE REFERENCES "Dutyslip" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
;
CREATE INDEX "Dutyslipsms_e93cb7eb" ON "Dutyslipsms" ("created_by_id");
CREATE INDEX "Dutyslipsms_9ccf0ba6" ON "Dutyslipsms" ("updated_by_id");
CREATE TABLE "Vendor" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "vendor_name" varchar(128) NOT NULL, "vendor_phoneno" varchar(10) NOT NULL, "vendor_email" varchar(70) NOT NULL UNIQUE, "vendor_picture" varchar(100) NULL, "vendor_joined_date" date NULL, "vendor_payment_type" varchar(20) NULL, "vendor_agreement_start_date" date NOT NULL, "vendor_agreement_end_date" date NOT NULL, "vendor_documents" varchar(100) NULL, "bank_name" varchar(100) NULL, "beneficiary_account_name" varchar(50) NULL, "accountno" varchar(20) NULL, "ifsc" varchar(10) NULL, "remarks" varchar(200) NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"), "vendor_address_id" integer NOT NULL REFERENCES "rapido_location" ("id"), "vendor_type_id" integer NOT NULL REFERENCES "Vendortype" ("id"), "is_active" bool NOT NULL);
;
CREATE UNIQUE INDEX "Vendor_vendor_name_fd66f0b0_uniq" ON "Vendor" ("vendor_name", "vendor_email");
CREATE INDEX "Vendor_e93cb7eb" ON "Vendor" ("created_by_id");
CREATE INDEX "Vendor_9ccf0ba6" ON "Vendor" ("updated_by_id");
CREATE INDEX "Vendor_d0af88f1" ON "Vendor" ("vendor_address_id");
CREATE INDEX "Vendor_313fc444" ON "Vendor" ("vendor_type_id");
CREATE TABLE "City_ratecard" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "vehicle_varient" varchar(128) NULL, "fgr" real NOT NULL, "base_rate" real NOT NULL, "extra_kmrate" real NOT NULL, "extra_hrrate" real NOT NULL, "night_batta" real NOT NULL, "category_id" integer NOT NULL REFERENCES "Category" ("id"), "city_id" integer NOT NULL REFERENCES "City" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "service_type_id" integer NOT NULL REFERENCES "Travelservicetype" ("id"), "slab_id" integer NOT NULL REFERENCES "Slab" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE UNIQUE INDEX "City_ratecard_city_id_37d59b92_uniq" ON "City_ratecard" ("city_id", "category_id", "slab_id");
CREATE INDEX "City_ratecard_b583a629" ON "City_ratecard" ("category_id");
CREATE INDEX "City_ratecard_c7141997" ON "City_ratecard" ("city_id");
CREATE INDEX "City_ratecard_e93cb7eb" ON "City_ratecard" ("created_by_id");
CREATE INDEX "City_ratecard_8f1d2d79" ON "City_ratecard" ("service_type_id");
CREATE INDEX "City_ratecard_7a8a3417" ON "City_ratecard" ("slab_id");
CREATE INDEX "City_ratecard_9ccf0ba6" ON "City_ratecard" ("updated_by_id");
CREATE TABLE "Company_city_ratecard" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "vehicle_varient" varchar(128) NULL, "fgr" real NOT NULL, "base_rate" real NOT NULL, "extra_kmrate" real NOT NULL, "extra_hrrate" real NOT NULL, "night_batta" real NOT NULL, "gst_no" varchar(128) NULL, "category_id" integer NOT NULL REFERENCES "Category" ("id"), "city_id" integer NOT NULL REFERENCES "City" ("id"), "company_id" integer NOT NULL REFERENCES "Company" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "service_type_id" integer NOT NULL REFERENCES "Travelservicetype" ("id"), "slab_id" integer NOT NULL REFERENCES "Slab" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE UNIQUE INDEX "Company_city_ratecard_company_id_e0060e13_uniq" ON "Company_city_ratecard" ("company_id", "city_id", "category_id", "slab_id");
CREATE INDEX "Company_city_ratecard_b583a629" ON "Company_city_ratecard" ("category_id");
CREATE INDEX "Company_city_ratecard_c7141997" ON "Company_city_ratecard" ("city_id");
CREATE INDEX "Company_city_ratecard_447d3092" ON "Company_city_ratecard" ("company_id");
CREATE INDEX "Company_city_ratecard_e93cb7eb" ON "Company_city_ratecard" ("created_by_id");
CREATE INDEX "Company_city_ratecard_8f1d2d79" ON "Company_city_ratecard" ("service_type_id");
CREATE INDEX "Company_city_ratecard_7a8a3417" ON "Company_city_ratecard" ("slab_id");
CREATE INDEX "Company_city_ratecard_9ccf0ba6" ON "Company_city_ratecard" ("updated_by_id");
CREATE TABLE "Company_booker" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "label" varchar(128) NULL, "booking_phoneno" varchar(10) NULL, "booking_email" varchar(254) NULL, "company_id" integer NOT NULL REFERENCES "Company" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE UNIQUE INDEX "Company_booker_company_id_ef4d42ac_uniq" ON "Company_booker" ("company_id", "label", "booking_phoneno");
CREATE INDEX "Company_booker_447d3092" ON "Company_booker" ("company_id");
CREATE INDEX "Company_booker_e93cb7eb" ON "Company_booker" ("created_by_id");
CREATE INDEX "Company_booker_9ccf0ba6" ON "Company_booker" ("updated_by_id");
CREATE TABLE "Cancelsms" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "created_by_ip_address" varchar(128) NULL, "updated_date" datetime NULL, "updated_by_ip_address" varchar(128) NULL, "useremailsent" bool NOT NULL, "usersmssent" bool NOT NULL, "usersmsdelivery" bool NOT NULL, "userstatus" varchar(128) NULL, "driversmssent" bool NOT NULL, "driversmsdelivery" bool NOT NULL, "driverstatus" varchar(128) NULL, "booking_id" integer NOT NULL UNIQUE REFERENCES "Bookings" ("id"), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"));
;
CREATE INDEX "Cancelsms_e93cb7eb" ON "Cancelsms" ("created_by_id");
CREATE INDEX "Cancelsms_9ccf0ba6" ON "Cancelsms" ("updated_by_id");
CREATE TABLE "Smsforothers" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "booking_id" varchar(30) NOT NULL, "phoneno" varchar(10) NOT NULL, "message" varchar(300) NOT NULL, "emailsent" bool NOT NULL, "smssent" bool NOT NULL, "smsdelivery" bool NOT NULL, "status" varchar(128) NOT NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"));
CREATE INDEX "Smsforothers_e93cb7eb" ON "Smsforothers" ("created_by_id");
CREATE TABLE "Chauffeur_vehicel" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "vehicle_modelname" varchar(128) NULL, "vehicle_colour" varchar(128) NULL, "seat_capacity" integer NOT NULL, "fcexpairy_date" date NULL, "tax_expire_date" date NULL, "insurance_exp_date" date NULL, "vehicle_engine_no" varchar(30) NULL, "puc_exp" date NULL, "permit" varchar(128) NULL, "chauffeur_name" varchar(128) NULL, "chauffeur_phoneno" integer NOT NULL, "chauffeur_picture" varchar(100) NULL, "chauffeur_drivinglicense" varchar(120) NULL, "chauffeur_drivinglicense_expire_date" date NULL, "chauffeur_badgeno" varchar(128) NULL, "chauffeur_badge_expired_date" date NULL, "likes" integer NOT NULL, "ratings" integer NOT NULL, "is_active" bool NOT NULL, "created_date" datetime NOT NULL, "updated_date" datetime NULL, "created_by_ip_address" varchar(128) NULL, "updated_by_ip_address" varchar(128) NULL, "chauffeur_address" varchar(250) NULL, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id"), "updated_by_id" integer NULL REFERENCES "auth_user" ("id"), "vendor_id" integer NOT NULL REFERENCES "Vendor" ("id"), "police_verification" varchar(128) NULL, "vehicle_no" varchar(20) NOT NULL UNIQUE);
;
CREATE UNIQUE INDEX "Chauffeur_vehicel_vendor_id_31fc108f_uniq" ON "Chauffeur_vehicel" ("vendor_id", "vehicle_no", "chauffeur_phoneno", "chauffeur_name");
CREATE INDEX "Chauffeur_vehicel_e93cb7eb" ON "Chauffeur_vehicel" ("created_by_id");
CREATE INDEX "Chauffeur_vehicel_9ccf0ba6" ON "Chauffeur_vehicel" ("updated_by_id");
CREATE INDEX "Chauffeur_vehicel_96b1f972" ON "Chauffeur_vehicel" ("vendor_id");
CREATE TABLE "Billingsummary" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_date" datetime NOT NULL, "booking_id" varchar(128) NOT NULL UNIQUE, "client_name" varchar(128) NOT NULL, "user_name" varchar(128) NULL, "date_of_usage" date NULL, "date_out" date NULL, "date_in" date NULL, "city" varchar(128) NOT NULL, "duty_type" varchar(128) NULL, "vehicle_request" varchar(128) NULL, "h4_40_km_rate" integer NULL, "h8_80_KM_rate" integer NULL, "extra_hour_rate" integer NULL, "extra_km_rate" integer NULL, "outstation_min_km" integer NULL, "airport_trf_rate" real NULL, "km_out" integer NULL, "km_in" integer NULL, "total_km" real NULL, "time_out" real NULL, "time_in" real NULL, "total_hour" real NULL, "slab_used" varchar(128) NULL, "extra_km_run" integer NULL, "extra_hr_run" real NULL, "base_slab_rate" real NULL, "extra_km_amt" real NULL, "extra_hr_amt" real NULL, "total_amount" real NULL, "parking_toll" real NULL, "interstate_tax" real NULL, "day_batta" real NULL, "night_batta" real NULL, "total" real NULL, "gst" real NULL, "total_bill_amount" real NULL, "vendor_type" varchar(128) NULL, "vendor_name" varchar(128) NULL, "vehicle_no" varchar(128) NULL, "vendor_bill_no" varchar(128) NULL, "vbase_slab" real NULL, "vextra_km_amt" real NULL, "vextra_hr_amt" real NULL, "vtotal_amount" real NULL, "vparking" real NULL, "vinterstate_tax" real NULL, "vbatta" real NULL, "vendorpayble_amt" real NULL, "our_margin_amt" real NULL, "margin_percentage" real NULL, "status" bool NOT NULL, "comment" varchar(128) NULL, "other_amt" real NULL, "no_of_days" varchar(128) NULL, "sgst" varchar(128) NULL, "cgst" varchar(128) NULL, "company_gst" varchar(128) NULL, "company_pan" varchar(128) NULL, "reporting_time" varchar(128) NULL, "billing_address" varchar(250) NULL, "city_used" varchar(128) NULL, "booked_by" varchar(128) NULL, "code" varchar(128) NULL, "pickup" varchar(128) NULL, "drop" varchar(128) NULL, "pickuptime" varchar(128) NULL, "drivername" varchar(128) NULL, "driver_phoneno" varchar(128) NULL, "guest_phoneno" varchar(128) NULL, "fgr" varchar(128) NULL);
;
