# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-04 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import rapido.models


class Migration(migrations.Migration):

    dependencies = [
        ('rapido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_id',
            field=models.CharField(default=rapido.models.increment_booking_number, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
