# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-05 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapido', '0002_auto_20171204_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phoneno',
            field=models.CharField(max_length=15),
        ),
    ]
