# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-27 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapido', '0006_auto_20171214_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_booker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('booking_name', models.CharField(blank=True, max_length=128, null=True)),
                ('booking_phoneno', models.CharField(blank=True, max_length=10, null=True)),
                ('booking_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapido.Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_booker_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_booker_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Company_booker',
            },
        ),
        migrations.AlterUniqueTogether(
            name='company_booker',
            unique_together=set([('company', 'booking_name', 'booking_phoneno')]),
        ),
    ]
