# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-30 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapido', '0008_auto_20180129_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelsms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by_ip_address', models.CharField(blank=True, max_length=128, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by_ip_address', models.CharField(blank=True, max_length=128, null=True)),
                ('useremailsent', models.BooleanField(default=False)),
                ('usersmssent', models.BooleanField(default=False)),
                ('usersmsdelivery', models.BooleanField(default=False)),
                ('userstatus', models.CharField(blank=True, max_length=128, null=True)),
                ('driversmssent', models.BooleanField(default=False)),
                ('driversmsdelivery', models.BooleanField(default=False)),
                ('driverstatus', models.CharField(blank=True, max_length=128, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rapido.Bookings')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelsms', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelsmsupdate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cancelsms',
            },
        ),
    ]
