# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-01 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapido', '0009_cancelsms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur_vehicel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=10, unique=True)),
                ('vehicle_modelname', models.CharField(blank=True, max_length=128, null=True)),
                ('vehicle_colour', models.CharField(blank=True, max_length=128, null=True)),
                ('seat_capacity', models.IntegerField()),
                ('fcexpairy_date', models.DateField(blank=True, null=True)),
                ('tax_expire_date', models.DateField(blank=True, null=True)),
                ('insurance_exp_date', models.DateField(blank=True, null=True)),
                ('vehicle_engine_no', models.CharField(max_length=30)),
                ('puc_exp', models.CharField(max_length=30)),
                ('permit', models.CharField(max_length=30)),
                ('chauffeur_name', models.CharField(max_length=128)),
                ('chauffeur_phoneno', models.CharField(max_length=10, unique=True)),
                ('chauffeur_picture', models.ImageField(blank=True, default='chaffeur_pics/img_avatar3.png', upload_to='chaffeur_pics')),
                ('chauffeur_drivinglicense', models.CharField(max_length=20)),
                ('chauffeur_drivinglicense_expire_date', models.DateField()),
                ('chauffeur_badgeno', models.CharField(max_length=10)),
                ('chauffeur_badge_expired_date', models.DateField()),
                ('likes', models.IntegerField(default=0)),
                ('ratings', models.IntegerField(blank=True, default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('created_by_ip_address', models.CharField(blank=True, max_length=128, null=True)),
                ('updated_by_ip_address', models.CharField(blank=True, max_length=128, null=True)),
                ('chauffeur_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rapido.Location')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chauufer_vehicle_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chauffer_vehicle_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapido.Vendor')),
            ],
            options={
                'db_table': 'Chauffeur_vehicel',
            },
        ),
        migrations.AlterUniqueTogether(
            name='chauffeur_vehicel',
            unique_together=set([('vendor', 'vehicle_no', 'chauffeur_phoneno', 'chauffeur_name')]),
        ),
    ]
