# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-01 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapido', '0010_auto_20180201_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='chauffeur_address',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
