# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-01 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapido', '0011_auto_20180201_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur_vehicel',
            name='police_verification',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='chauffeur_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='chauffeur_badge_expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='chauffeur_badgeno',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='chauffeur_drivinglicense',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='chauffeur_drivinglicense_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='chauffeur_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='chauffeur_picture',
            field=models.ImageField(blank=True, default='chaffeur_pics/img_avatar3.png', null=True, upload_to='chaffeur_pics'),
        ),
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='permit',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='puc_exp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='vehicle_engine_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
