# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-07 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapido', '0012_auto_20180201_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='puc_exp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
