# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-07 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapido', '0013_auto_20180207_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smsforothers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.CharField(max_length=30)),
                ('phoneno', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=300)),
                ('emailsent', models.BooleanField(default=False)),
                ('smssent', models.BooleanField(default=False)),
                ('smsdelivery', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smsforothers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Smsforothers',
            },
        ),
    ]
