# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-12 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapido', '0015_auto_20180209_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur_vehicel',
            name='vehicle_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
