# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-28 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapido', '0018_auto_20180314_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='emailcopy',
            field=models.ImageField(blank=True, null=True, upload_to='email_copy'),
        ),
    ]
