"""
Django settings for rapido_travels project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o(%=+ysuf4lb)t$v0^gboz992r)&564=^6e@@c+c00v+27@az9'

# SECURITY WARNING: don't run with debug turned on in production!

# comment below two lines while hosting in server
DEBUG = False


ALLOWED_HOSTS = ['*']

# un comment these two lines while hosting in server and specify the host name within braces
#DEBUG = False

#ALLOWED_HOSTS = ['139.59.23.126']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rapido',
    'rest_framework',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rapido_travels.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rapido_travels.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.sqlite3',
         'NAME': os.path.join(BASE_DIR, 'rapido_newdb2.sqlite3'),
       #   'ENGINE': 'django.db.backends.mysql',
       #   'NAME': 'rapido',
       # 'USER': 'root',
       # 'PASSWORD': 'root',
       # 'HOST': 'localhost',
       # 'PORT': '3306',

    }
}


#-------e mail-------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS = True

EMAIL_HOST = 'mail.rapidotravels.co.in'

EMAIL_HOST_USER = 'test1@rapidotravels.co.in'

#Must generate specific password for your app in [gmail settings][1]

EMAIL_HOST_PASSWORD = 'rapido@2018'

EMAIL_PORT = 25

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# rapido e mail credentials

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# EMAIL_USE_TLS = True

# EMAIL_HOST = 'bh-in-21.webhostbox.net'

# EMAIL_HOST_USER = 'test@rapidotravels.co.in'

# #Must generate specific password for your app in [gmail settings][1]

# EMAIL_HOST_PASSWORD = 'test123$%'

# EMAIL_PORT = 465

# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# email close


# e mail sending mine creditials ----------
#For email
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# EMAIL_USE_TLS = True

# EMAIL_HOST = 'smtp.gmail.com'

# EMAIL_HOST_USER = 'manju24.rymec@gmail.com'

# #Must generate specific password for your app in [gmail settings][1]
# EMAIL_HOST_PASSWORD = 'manju24anna'

# EMAIL_PORT = 587

# #This did the trick
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
#============= e mail colse ------------------

# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'me@gmail.com'
# EMAIL_HOST_PASSWORD = 'password'


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# URL prefix for static files.
# Example: "http://example.com/static/", "http://static.example.com/"
STATIC_URL = '/static/'

# Additional locations of static files
STATICFILES_DIRS = [os.path.join(BASE_DIR,'newstatic'),]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


TEMPLATE_CONTEXT_PROCESSORS = (
   'django.contrib.auth.context_processors.auth',
   'django.core.context_processors.debug',
   'django.core.context_processors.i18n',
   'django.core.context_processors.media',
   'django.core.context_processors.static',
   'django.core.context_processors.tz',
   'django.contrib.messages.context_processors.messages',
   'social.apps.django_app.context_processors.backends',
   'social.apps.django_app.context_processors.login_redirect',
)

PIPELINE_COMPILERS = (
  'react.utils.pipeline.JSXCompiler',
)